apps/direccion/urls.py
from django.urls import path
from .views import (vPrincipal, vPrinDirec, vPerfil, vCambiarAvatar, vCambiarNombreUsuario, vCambiarPassword, vCorreosNotificacion, vActividadEstatus,
                    vRegistroActividades, vEliminarActividades, vEditarActividad, vObtenerActividades,
                    vEditarCheckObjetivo, vEliminarObjetivo, vEditarObjetivo, vAgregarObjetivos, vEditarComentario,
                    vAgregarEvidencias, vEliminarEvidencias, vEditarPrioridad)
from .download_evidences import descargarEvidenciasZip
app_name = 'direccion'

urlpatterns = [
    path('', vPrinDirec, name = 'prinDirect'),
    path('perfil/', vPerfil, name = 'perfil'),
    path('actividades/', vPrincipal, name = 'principal'),
    #Activities
    path('actividad/agregar', vRegistroActividades, name = 'rActividad'),
    path('actividad/<int:id>/eliminar', vEliminarActividades, name = 'eActividad'),
    #Objetivos
    path('actividad/objetivo/<int:id>/eliminar', vEliminarObjetivo, name = 'eObjetivo'),
    #Evidencias
    path('actividad/evidencias/agregar', vAgregarEvidencias, name = 'rEvidencia'),
    path('actividad/evidencias/<int:id>/eliminar', vEliminarEvidencias, name = 'eEvidencia'),
    path('actividad/<int:id>/evidencias/descargar', descargarEvidenciasZip, name = 'desEvidencias'),
    #Ajax
    path('ajax/actividad/objetivo/editarcheck', vEditarCheckObjetivo),
    path('ajax/actividad/<int:id>/editar', vEditarActividad, name = 'edActividad'),
    path('ajax/actividad/objetivo/<int:id>/editar', vEditarObjetivo, name = 'edObjetivo'),
    path('ajax/actividad/objetivo/agregar', vAgregarObjetivos, name = 'aObjetivo'),
    path('ajax/actividades/', vObtenerActividades, name = 'obActividades'),
    path('ajax/actividad/<int:id>/comentarios/editar', vEditarComentario, name = 'eComentario'),
    path('ajax/actividad/<int:id>/status/editar', vActividadEstatus, name = 'edEstatusAct'),
    path('ajax/actividad/prioridad', vEditarPrioridad),
    #Acciones del perfil
    path('titular/avatar/cambiar', vCambiarAvatar, name = 'eAvatar'),
    path('titular/nombre/cambiar', vCambiarNombreUsuario, name = 'eNombreUsu'),
    path('titular/password/cambiar', vCambiarPassword, name = 'ePassword'),
    path('titular/correos/editar', vCorreosNotificacion, name = 'edCorreoNoti'),
]

semaforo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.direccion.views import vLogin, vLogout, vRegistroUsuarios


urlpatterns = [
    path('', vLogin, name = 'login'),
    path('direccion/', include('apps.direccion.urls', namespace = 'direccion')),
    path('admin/', include('apps.admin.urls', namespace = 'admin')),
    path('logout/', vLogout, name = 'logout'),
    path('registro/', vRegistroUsuarios, name = 'rUsuario'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/direccion/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Direcciones(models.Model):
    nombre = models.CharField(max_length = 100)
    codename = models.CharField(max_length = 5)
    see_in_select = models.BooleanField(default = True)
    see_in_list = models.BooleanField(default = True)
    is_active = models.BooleanField(default = True)
    titular = models.OneToOneField('direccion.Usuarios', on_delete = models.CASCADE, null = True, blank = True)
    subdireccion = models.ForeignKey('self', on_delete = models.SET_NULL, null = True, blank = True, related_name = 'subdir')
    def __str__(self):
        return '{}'.format(self.nombre)

class Usuarios(AbstractUser):
    direccion = models.ForeignKey(Direcciones, null = True, blank = True, on_delete = models.PROTECT)
    avatar = models.ImageField(upload_to = 'avatar/', null = True, blank = True)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

class Permisos(models.Model):
    assign_all = models.BooleanField(default = False)
    see_all = models.BooleanField(default = False)
    see_panel = models.BooleanField(default = False)
    delete_all = models.BooleanField(default = False)
    change_priority = models.BooleanField(default = False)
    usuario = models.OneToOneField(Usuarios, blank = True, null = True, on_delete = models.CASCADE, related_name = 'permisos')

class Actividades(models.Model):
    class Meta:
        ordering = ['prioridad', '-timestamp']

    prioridad_choices = [
        (1, 'Alta'),
        (2, 'Media'),
        (3, 'Baja')
    ]
    nombre = models.CharField(max_length = 500)
    folio = models.CharField(max_length = 10, null = True, blank = True)
    timestamp = models.DateTimeField(auto_now_add = True)
    comentarios = models.CharField(max_length = 700, null = True, blank = True,  default = '')
    prioridad = models.SmallIntegerField(default = 2, choices = prioridad_choices)
    direccion = models.ForeignKey(Direcciones, null = True, blank = True, related_name = 'actividades' , on_delete = models.CASCADE)
    is_cancelled = models.BooleanField(default = False)    
    usuario = models.ForeignKey(Usuarios, blank = True, on_delete = models.CASCADE)

    def get_priority_class(self):
        if self.prioridad == 1:
            return 'high'
        elif self.prioridad == 2:
            return 'medium'
        elif self.prioridad == 3:
            return 'low'
        else:
            return 'none'

    def get_priority(self):
        return dict(self.prioridad_choices).get(self.prioridad, 'No especificado')

    def get_porcent(self):
        total = self.objetivos.count()
        total_done = self.objetivos.filter(is_done = True).count()
        return getPercentActivity(total_done, total)
    
    def get_light(self):
        total = self.objetivos.count()
        total_done = self.objetivos.filter(is_done = True).count()
        return getLightActivity(total_done, total)

def act_directory_path(instance, filename):
    return 'evidencias/{0}/{1}'.format(instance.actividad.folio,filename)

class Evidencias(models.Model):
    evidencia = models.FileField(upload_to = act_directory_path, null = True, blank = True)
    nombre = models.CharField(max_length = 500)
    timestamp = models.DateTimeField(auto_now_add = True)
    actividad = models.ForeignKey(Actividades, null = True, blank = True, related_name = 'evidencias' , on_delete = models.CASCADE)

class Objetivos(models.Model):
    nombre = models.CharField(max_length = 500)
    is_done = models.BooleanField(default = False)
    actividad = models.ForeignKey(Actividades, null = True, blank = True, related_name = 'objetivos' , on_delete = models.CASCADE)

def getPercentActivity(num, total):
    try:
        percent = (100 * num)/total
        return round(percent)
    except:
        return 0

def getLightActivity(num, total):
    red_color = '#f44336'
    green_color = '#4caf50'
    yellow_color = '#ffeb3b'
    green_light = 100
    yellow_light = 70
    try:
        percent = getPercentActivity(num, total)
        if percent == green_light:
            return green_color
        elif percent < green_light and percent >= yellow_light:
            return yellow_color
        elif percent < yellow_light:
            return red_color
    except:
        return red_color

class Correos_Notificacion(models.Model):
    correo_inst = models.EmailField(null = True, blank = True)
    correo_per = models.EmailField(null = True, blank = True)
    usuario = models.OneToOneField(Usuarios, related_name = 'correos', null = True, blank = True, on_delete = models.CASCADE)

templates/customtags/activity.html
{% load static %}
{% load customtags %}
<ul class="collapsible popout">
    {% for act in activities %}
    <li>
        <div class="collapsible-header {% if act.is_cancelled %}cancelled{% endif %}">
            <i class="material-icons">spellcheck</i><span class="act-name">{{act.nombre}}
            </span>
            <div class="priority z-depth-1 {{act.get_priority_class}}"></div>
            <span class="badge white-text" style="background-color: {{act.get_light}}">{{act.get_porcent}}%</span>
        </div>
        <div class="collapsible-body">
            {% if act.usuario == user %}
            <div class="row right-align">
                <div class="switch">
                    <label>
                        Cancelado
                        <input type="checkbox" class="cancel-act" data-url="{% url 'direccion:edEstatusAct' act.id %}"
                            {% if act.is_cancelled %}checked{% endif %}>
                        <span class="lever"></span>
                    </label>
                </div>
            </div>
            {% endif %}
            <span>Creado por:
                <b>{% if act.usuario == user %}Usted{% else %}{{act.usuario.get_full_name}}{% endif %}</b></span>
            <br>
            <span>Fecha de creación: <b>{{act.timestamp}}</b></span>
            <br>
            {% if act.usuario == user or user.permisos.change_priority %}
            <span>Prioridad: {% prioritySelect act.prioridad act.id %}</span>
            {% else %}
            <span>Prioridad: {{act.get_priority}}</span>
            {% endif %}
            <div class="row right-align">
                <a href="{% url 'direccion:eComentario' act.id %}"
                    class="btn blue {% if act.direccion == user.direccion %}add-comment{% else %}show-comment{% endif %}"
                    data-comment="{% if act.comentarios %}{{act.comentarios}}{% endif %}"><i
                        class="material-icons">comment</i></a>
                {% if act.usuario == user or user.permisos.delete_all %}
                <a href="{% url 'direccion:eActividad' act.pk %}" class="btn red del-act">
                    <i class="material-icons">delete</i>
                </a>
                <a class="btn blue edit-act" href="{% url 'direccion:edActividad' act.id %}">
                    <i class="material-icons">edit</i>
                </a>
                <a class="btn blue add-saved-objs"><i class="material-icons">add</i></a>
                {% endif %}
            </div>
            <div class="act-objs" data-id="{{act.id}}">
                <table>
                    <thead>
                        <tr>
                            <th class="center-align">Nombre</th>
                            <th class="right-align">Hecho</th>
                            <th class="center-align">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <h5 class="center-align">Objetivos</h5>
                        <br>
                        {% for obj in act.objetivos.all %}
                        <tr>
                            <td>{{obj.nombre}}</td>
                            <td class="right-align">
                                {% if act.direccion == user.direccion or act.usuario == user %}
                                <label class="secondary-content"><input type="checkbox" class="obj-saved"
                                        {{ obj.is_done|yesno:"checked,," }} value="{{obj.id}}"><span></span>
                                </label>
                                {% else %}
                                <span>{{ obj.is_done|yesno:"Sí,No,No" }}</span>
                                {% endif %}
                            </td>
                            <td class="center-align">
                                {% if act.usuario == user or user.permisos.delete_all %}
                                <a class="btn-small red del-obj" href="{% url 'direccion:eObjetivo' obj.id %}">
                                    <i class="material-icons">delete</i>
                                </a>
                                <a class="btn-small blue edit-obj" href="{% url 'direccion:edObjetivo' obj.id %}">
                                    <i class="material-icons">edit</i>
                                </a>
                                {% else %}
                                Sin acciones
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="act-evidencias">
                <br>
                <h5 class="center-align">Evidencias</h5>
                <div class="row right-align">
                    {% if act.evidencias.count > 0 %}
                    <a class="btn blue" href="{% url 'direccion:desEvidencias' act.id %}"><i
                            class="material-icons left">file_download</i>zip</a>
                    {% endif %}
                    <a class="btn blue add-saved-files"><i class="material-icons">add</i></a>
                </div>
                <div class="cont-file" style="display:none;">
                    <form action="{% url 'direccion:rEvidencia' %}" method="post" style=""
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col l8 offset-l2 m12 s12">
                                <input type="hidden" name="actividad" value="{{act.id}}">
                                <div class="file-field input-field">
                                    <div class="btn vino">
                                        <span>Seleccionar</span>
                                        <input type="file" name="evidencias"
                                            accept=".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document, .xls, .xlsx, application/msexcel, application/x-msexcel, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.presentationml.presentation, .ppt, .pptx, application/vnd.ms-powerpoint, application/pdf, image/jpeg, image/png"
                                            multiple>
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path" type="text">
                                        <span class="helper-text">10 MB es el peso límite por archivo</span>
                                    </div>
                                </div>
                                <ul class="collection"></ul>
                                <div class="row right-align">
                                    <button class="btn-small green"><i class="material-icons">check</i></button>
                                    <a class="btn-small red del-new-files"><i class="material-icons">clear</i></a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th class="center-align">Nombre</th>
                            <th class="center-align">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for evi in act.evidencias.all %}
                        <tr>
                            <td>{{evi.nombre}}</td>
                            <td class="center-align">
                                <a class="btn-small red del-file" href="{% url 'direccion:eEvidencia' evi.id %}"><i
                                        class="material-icons">delete</i></a>
                                <a class="btn-small blue" href="{% get_media_prefix %}{{evi.evidencia}}" download>
                                    <i class="material-icons">file_download</i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

templates/customtags/activity_old.html
{% load static %}
{% load customtags %}
<ul class="collapsible popout">
    <div class="divider"></div>
    <br>
    {% for act in activities %}
    {% if not act.get_porcent == 100 and not act.is_cancelled %}
    <li>
        <div class="collapsible-header {% if act.is_cancelled %}cancelled{% endif %}">
            <i class="material-icons">spellcheck</i><span class="act-name">{{act.nombre}}</span>
            <span style="padding-left: 10px;">({{ act.timestamp|date:"Y" }})</span>
            <div class="priority z-depth-1 {{act.get_priority_class}}"></div>
            <span class="badge white-text" style="background-color: {{act.get_light}}">{{act.get_porcent}}%</span>
        </div>
        <div class="collapsible-body">
            {% if act.usuario == user %}
            <div class="row right-align">
                <div class="switch">
                    <label>
                        Cancelado
                        <input type="checkbox" class="cancel-act" data-url="{% url 'direccion:edEstatusAct' act.id %}"
                            {% if act.is_cancelled %}checked{% endif %}>
                        <span class="lever"></span>
                    </label>
                </div>
            </div>
            {% endif %}
            <span>Creado por:
                <b>{% if act.usuario == user %}Usted{% else %}{{act.usuario.get_full_name}}{% endif %}</b></span>
            <br>
            <span>Fecha de creación: <b>{{act.timestamp}}</b></span>
            <br>
            {% if act.usuario == user or user.permisos.change_priority %}
            <span>Prioridad: {% prioritySelect act.prioridad act.id %}</span>
            {% else %}
            <span>Prioridad: {{act.get_priority}}</span>
            {% endif %}
            <div class="row right-align">
                <a href="{% url 'direccion:eComentario' act.id %}"
                    class="btn blue {% if act.direccion == user.direccion %}add-comment{% else %}show-comment{% endif %}"
                    data-comment="{% if act.comentarios %}{{act.comentarios}}{% endif %}"><i
                        class="material-icons">comment</i></a>
                {% if act.usuario == user or user.permisos.delete_all %}
                <a href="{% url 'direccion:eActividad' act.pk %}" class="btn red del-act">
                    <i class="material-icons">delete</i>
                </a>
                <a class="btn blue edit-act" href="{% url 'direccion:edActividad' act.id %}">
                    <i class="material-icons">edit</i>
                </a>
                <a class="btn blue add-saved-objs"><i class="material-icons">add</i></a>
                {% endif %}
            </div>
            <div class="act-objs" data-id="{{act.id}}">
                <table>
                    <thead>
                        <tr>
                            <th class="center-align">Nombre</th>
                            <th class="right-align">Hecho</th>
                            <th class="center-align">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <h5 class="center-align">Objetivos</h5>
                        <br>
                        {% for obj in act.objetivos.all %}
                        <tr>
                            <td>{{obj.nombre}}</td>
                            <td class="right-align">
                                {% if act.direccion == user.direccion or act.usuario == user %}
                                <label class="secondary-content"><input type="checkbox" class="obj-saved"
                                        {{ obj.is_done|yesno:"checked,," }} value="{{obj.id}}"><span></span>
                                </label>
                                {% else %}
                                <span>{{ obj.is_done|yesno:"Sí,No,No" }}</span>
                                {% endif %}
                            </td>
                            <td class="center-align">
                                {% if act.usuario == user or user.permisos.delete_all %}
                                <a class="btn-small red del-obj" href="{% url 'direccion:eObjetivo' obj.id %}">
                                    <i class="material-icons">delete</i>
                                </a>
                                <a class="btn-small blue edit-obj" href="{% url 'direccion:edObjetivo' obj.id %}">
                                    <i class="material-icons">edit</i>
                                </a>
                                {% else %}
                                Sin acciones
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="act-evidencias">
                <br>
                <h5 class="center-align">Evidencias</h5>
                <div class="row right-align">
                    {% if act.evidencias.count > 0 %}
                    <a class="btn blue" href="{% url 'direccion:desEvidencias' act.id %}"><i
                            class="material-icons left">file_download</i>zip</a>
                    {% endif %}
                    <a class="btn blue add-saved-files"><i class="material-icons">add</i></a>
                </div>
                <div class="cont-file" style="display:none;">
                    <form action="{% url 'direccion:rEvidencia' %}" method="post" style=""
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col l8 offset-l2 m12 s12">
                                <input type="hidden" name="actividad" value="{{act.id}}">
                                <div class="file-field input-field">
                                    <div class="btn vino">
                                        <span>Seleccionar</span>
                                        <input type="file" name="evidencias"
                                            accept=".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document, .xls, .xlsx, application/msexcel, application/x-msexcel, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.presentationml.presentation, .ppt, .pptx, application/vnd.ms-powerpoint, application/pdf, image/jpeg, image/png"
                                            multiple>
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path" type="text">
                                        <span class="helper-text">10 MB es el peso límite por archivo</span>
                                    </div>
                                </div>
                                <ul class="collection"></ul>
                                <div class="row right-align">
                                    <button class="btn-small green"><i class="material-icons">check</i></button>
                                    <a class="btn-small red del-new-files"><i class="material-icons">clear</i></a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th class="center-align">Nombre</th>
                            <th class="center-align">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for evi in act.evidencias.all %}
                        <tr>
                            <td>{{evi.nombre}}</td>
                            <td class="center-align">
                                <a class="btn-small red del-file" href="{% url 'direccion:eEvidencia' evi.id %}"><i
                                        class="material-icons">delete</i></a>
                                <a class="btn-small blue" href="{% get_media_prefix %}{{evi.evidencia}}" download>
                                    <i class="material-icons">file_download</i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </li>
    {% endif %}
    {% empty %}
    {% endfor %}
</ul>

templates/customtags/directActAll.html
{% load customtags %}
{% load static %}
{% for direct in activities %}
<div class="row">
    <div class="col l2 center-align">
        {% if direct.titular.avatar %}
        <img src="{% get_media_prefix %}{{direct.titular.avatar}}" alt="" class="responsive-img">
        {% else %}
        <img src="{% static 'images/avatar.png' %}" alt="" class="avatar-filter responsive-img">
        {% endif %}
    </div>
    <div class="col l10">
        <h5>{{direct.nombre}}</h5>
        <h6>Titular: {% if direct.titular %}{{direct.titular.first_name}}{% else %}No asignado{% endif %}</h6>
    </div>
</div>
{% getNewActivitiesByYear direct user current_year %}
{% getOldActivitiesByYear direct user current_year %}
<br><br><br>
{% endfor %}

templates/customtags/directActFilter.html
{% load customtags %}
{% load static %}
<div class="row">
    <br>
    <div class="row">
        <div class="col l2 center-align">
            {% if direct.titular.avatar %}
            <img src="{% get_media_prefix %}{{direct.titular.avatar}}" alt="" class="responsive-img">
            {% else %}
            <img src="{% static 'images/avatar.png' %}" alt="" class="avatar-filter responsive-img">
            {% endif %}
        </div>
        <div class="col l10">
            <h5>{{direct.nombre}}</h5>
            <h6>Titular: {{direct.titular.first_name}}</h6>
        </div>
    </div>
    {% getNewActivitiesByYear direct user current_year %}
    {% getOldActivitiesByYear direct user current_year %}
</div>

templates/customtags/priority_select.html
<select class="prioridad" class="browser-default" style="display: inline; width: 80px; height: 35px;"
    data-default="{{opt_selected}}" data-act="{{act_id}}">
    {% for value, choice in choices %}
    <option value="{{value}}" {% if opt_selected == value %}selected{% endif %}>{{choice}}
    </option>
    {% endfor %}
</select>

templates/customtags/selectDirectAll.html
<select name="direccion" id="id_direccion">
    {% for dir in dirAll %}
    <option value="{{dir.id}}">{{dir.nombre}}</option>
    {% endfor %}
</select>
<label for="id_direccion">Seleccione una dirección</label>

templates/customtags/selectDirectFilter.html
{% if dirFilter.count > 0 or user_dir %}
<div class="input-field">
    <select name="direccion" id="id_direccion">
        {% if user_dir %}
        <option value="{{user_dir.id}}" selected>Mi dirección</option>
        {% endif %}
        {% for dir in dirFilter %}
        <option value="{{dir.id}}">{{dir.nombre}}</option>
        {% endfor %}
    </select>
    <label for="id_direccion">Seleccione una dirección</label>
</div>
{% endif %}