apps/admin/urls.py
from django.urls import path
from .views import (
    vPrinAdmin, vPrinUsuario, vPrinDireccion, vRegistroUsuarios, vRegistroDirecciones, vEliminarDireccion,
    vCambiarContrasena, vEliminarUsuario, vResetDireccion, vEditarDireccion
)
app_name = 'admin'

urlpatterns = [
    path('', vPrinAdmin, name = 'prinAdmin'),
    #Usuarios
    path('usuarios', vPrinUsuario, name = 'prinUsuario'),
    path('usuario/agregar', vRegistroUsuarios, name = 'rUsuario'),
    path('usuario/<int:id>/cambiarcontra', vCambiarContrasena, name = 'cambiarPass'),
    path('usuario/<int:id>/eliminar', vEliminarUsuario, name = 'eUsuario'),
    #Direcciones
    path('direcciones', vPrinDireccion, name = 'prinDireccion'),
    path('direccion/agregar', vRegistroDirecciones, name = 'rDireccion'),
    path('direccion/<int:id>/editar', vEditarDireccion, name = 'edDireccion'),
    path('direccion/<int:id>/eliminar', vEliminarDireccion, name = 'eDireccion'),
    path('direccion/<int:id>/reset', vResetDireccion, name = 'resetDireccion'),
]

apps/direccion/urls.py
from django.urls import path
from .views import (vPrincipal, vPrinDirec, vPerfil, vCambiarAvatar, vCambiarNombreUsuario, vCambiarPassword, vCorreosNotificacion, vActividadEstatus,
                    vRegistroActividades, vEliminarActividades, vEditarActividad, vObtenerActividades,
                    vEditarCheckObjetivo, vEliminarObjetivo, vEditarObjetivo, vAgregarObjetivos, vEditarComentario,
                    vAgregarEvidencias, vEliminarEvidencias, vEditarPrioridad)
from .download_evidences import descargarEvidenciasZip
app_name = 'direccion'

urlpatterns = [
    path('', vPrinDirec, name = 'prinDirect'),
    path('perfil/', vPerfil, name = 'perfil'),
    path('actividades/', vPrincipal, name = 'principal'),
    #Activities
    path('actividad/agregar', vRegistroActividades, name = 'rActividad'),
    path('actividad/<int:id>/eliminar', vEliminarActividades, name = 'eActividad'),
    #Objetivos
    path('actividad/objetivo/<int:id>/eliminar', vEliminarObjetivo, name = 'eObjetivo'),
    #Evidencias
    path('actividad/evidencias/agregar', vAgregarEvidencias, name = 'rEvidencia'),
    path('actividad/evidencias/<int:id>/eliminar', vEliminarEvidencias, name = 'eEvidencia'),
    path('actividad/<int:id>/evidencias/descargar', descargarEvidenciasZip, name = 'desEvidencias'),
    #Ajax
    path('ajax/actividad/objetivo/editarcheck', vEditarCheckObjetivo),
    path('ajax/actividad/<int:id>/editar', vEditarActividad, name = 'edActividad'),
    path('ajax/actividad/objetivo/<int:id>/editar', vEditarObjetivo, name = 'edObjetivo'),
    path('ajax/actividad/objetivo/agregar', vAgregarObjetivos, name = 'aObjetivo'),
    path('ajax/actividades/', vObtenerActividades, name = 'obActividades'),
    path('ajax/actividad/<int:id>/comentarios/editar', vEditarComentario, name = 'eComentario'),
    path('ajax/actividad/<int:id>/status/editar', vActividadEstatus, name = 'edEstatusAct'),
    path('ajax/actividad/prioridad', vEditarPrioridad),
    #Acciones del perfil
    path('titular/avatar/cambiar', vCambiarAvatar, name = 'eAvatar'),
    path('titular/nombre/cambiar', vCambiarNombreUsuario, name = 'eNombreUsu'),
    path('titular/password/cambiar', vCambiarPassword, name = 'ePassword'),
    path('titular/correos/editar', vCorreosNotificacion, name = 'edCorreoNoti'),
]

semaforo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.direccion.views import vLogin, vLogout, vRegistroUsuarios


urlpatterns = [
    path('', vLogin, name = 'login'),
    path('direccion/', include('apps.direccion.urls', namespace = 'direccion')),
    path('admin/', include('apps.admin.urls', namespace = 'admin')),
    path('logout/', vLogout, name = 'logout'),
    path('registro/', vRegistroUsuarios, name = 'rUsuario'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-mx">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'animate/animate.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block extrarlink %}
    {% endblock %}
    <style>
        .logo-rotation {
            -webkit-animation: rotation 10s infinite linear;
        }

        @-webkit-keyframes rotation {
            from {
                -webkit-transform: rotate(0deg);
            }

            to {
                -webkit-transform: rotate(359deg);
            }
        }

        {% block extrastyles %}
        {% endblock %}
    </style>
</head>

<body>
    {% block navbar %}
    <nav>
        <div class="nav-wrapper" style="background-color: #892541">
            <a href="#" class="brand-logo center">SEDEC</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if user.permisos.see_panel or user.is_staff %}
                <li><a target="_blank" href="{% url 'direccion:principal' %}">Panel</a></li>
                {% endif %}
                {% block extralist %}
                {% endblock %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:prinAdmin' %}">Principal</a></li>
                {% endif %}
                <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
            </ul>
        </div>
    </nav>
    <ul class="sidenav" id="mobile-demo">
        <li><a target="__blank" href="{% url 'direccion:principal' %}">Panel</a></li>
        {% block extralistmob %}
        {% endblock %}
        {% if user.is_staff %}
        <li><a href="{% url 'admin:prinAdmin' %}">Principal</a></li>
        {% endif %}
        <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
    </ul>
    {% endblock %}
    {% block maincontent %}
    {% endblock %}
    <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% include 'base/validaciones.html' %}
    {% block extrafunctions %}{% endblock %}
    {% block powered %}
    <footer class="center-align white">
        <br><br>
        <div class="center-align">
            <img src="{% static 'images/logo-esencia-dorado.png' %}" alt="" width="50px" class="logo-rotation">
        </div>
        <span class="grey-text lighten-2">© Powered by Unidad de Apoyo Técnico e Informático</span>
    </footer>
    {% endblock %}
</body>

</html>

templates/base/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Semáforo de actividades | Inicio{% endblock %}
{% block extrastyles %}
div#login{
padding: 40px 25px 25px 20px;
}
div#loginP{
margin-top:7%;
}
button.btn{
width : 100%;
background-color: #892541;
}
button.btn:hover{
background-color: #892541;
}
button.btn:focus{
background-color: #892541;
}

.input-field input[type=text]:focus {
border-bottom: 1px solid #b3935e !important;
box-shadow: 0 1px 0 0 #b3935e !important;
}
.input-field input[type=text]:focus+label {
color: #b3935e !important;
}

.input-field input[type=password]:focus {
border-bottom: 1px solid #b3935e !important;
box-shadow: 0 1px 0 0 #b3935e !important;
}
.input-field input[type=password]:focus+label {
color: #b3935e !important;
}
{% endblock %}
{% block navbar %}
{% endblock %}
{% block maincontent %}
<div class="container">
    <div class="row">
        <div class="col offset-l4 l4 z-depth-1 animated fadeIn" id="loginP">
            <div id="login">
                <div class="row center-align">
                    <img class="responsive-img" src="{% static 'images/logo_ctrl.png' %}" alt="" width="55%">
                </div>
                <form action="" method="post" id="formLogin">
                    {% csrf_token %}
                    <div class="input-field">
                        <input type="text" name="username" id="username">
                        <label for="username">Usuario</label>
                    </div>
                    <div class="input-field">
                        <input type="password" name="password" id="password">
                        <label for="password">Contraseña</label>
                    </div>
                    <div class="row center-align">
                        <button class="btn" id="accessLogin">Acceder</button>
                        <a href="{% url 'rUsuario' %}" class="btn-flat">Regístrate</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrafunctions %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        formLogin()
    })
</script>
{% endblock %}

templates/base/main.html
{% extends 'base/base.html' %}
{% load static %}
{% block extrarlink %}
<link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'slick/slick-theme.css' %}" />
{% endblock %}
{% block title %}Semáforo de actividades{% endblock %}
{% block extrastyles %}
.container{
width: 100% !important;
margin-top: 3%;
}
span.badge {
min-width: 4rem;
}
.vino{
background-color: #892541;
}
.txt-vino{
color: #892541;
}
.direction{
padding: 10px;
}
ul.collapsible{
overflow-y: scroll;
max-height: 54%;
}
.slick-prev:before {
color: #B8B8B8;
}
.slick-next:before {
color: #B8B8B8;
}
.bn-cont{
margin: 5px;
}
{% endblock %}
{% block extralist %}
<li><a href="{% url 'direccion:prinDirect' %}">Principal</a></li>
{% endblock %}
{% block extralistmob %}
<li><a href="{% url 'direccion:prinDirect' %}">Principal</a></li>
{% endblock %}
{% block maincontent %}
<div class="bn-cont">
    <button class="btn vino viewSlide hide-on-small-only"><i class="material-icons">view_carousel</i></button>
    <button class="btn vino viewModule hide-on-small-only"><i class="material-icons">view_module</i></button>
    <select class="browser-default right" name="" id="filter-year" style="width: 100px;">
        <option value="2019">2019</option>
        <option value="2020">2020</option>
        <option value="{{current_year}}" selected>{{current_year}}</option>
    </select>
    <h2 class="center-align txt-vino num-year">{{current_year}}</h2>
</div>
<div class="container">
    <input type="hidden" value="">
    <div class="directions-slider"></div>
    <div class="directions-module row"></div>
</div>
{% endblock %}
{% block extrafunctions %}
<script type="text/javascript" src="{% static 'slick/slick.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelector('#filter-year').addEventListener('change', function () {
            getActivities(this.value)
        })
        document.querySelector('.viewSlide').addEventListener('click', function () {
            $('.directions-slider').css('display', 'block')
            $('.directions-slider').get(0).slick.setPosition();
            $('.directions-module').css('display', 'none')
        })
        document.querySelector('.viewModule').addEventListener('click', function () {
            $('.directions-slider').css('display', 'none')
            $('.directions-module').css('display', 'block')
        })
        $('.directions-slider').slick({
            slidesToShow: 3,
            autoplay: true,
            autoplaySpeed: 10000
        });
        $('.directions-slider').hide()
        getActivities({{ current_year }})
    let year = document.querySelector('#filter-year').value
    setInterval(function () {
        let year = document.querySelector('#filter-year').value
        getActivities(year)
    }, 130000)
    });
    function getActivities(year) {
        let regEX = /^\d{4}$/
        if (regEX.test(year)) {
            $.getJSON("/direccion/ajax/actividades?year=" + year)
                .done(function (data) {
                    document.querySelector('.num-year').textContent = year
                    toastSuccess('Datos actualizados')
                    showActivitiesModule(data)
                    showActivitiesSlider(data)
                }).fail(function () {
                    toastError('Ha ocurrido un error')
                })
        } else {
            toastError('Ha ocurrido un error')
        }
    }

    function showActivitiesModule(data) {
        $('.directions-module .direction').remove()
        let cont_directions = document.querySelector('.directions-module')
        data.forEach(direction => {
            let parentDiv = document.createElement('div')
            let cardDiv = document.createElement('div')
            let rowDiv = document.createElement('div')
            let col1Div = document.createElement('div')
            let col2Div = document.createElement('div')
            let ul = document.createElement('ul')
            let img = document.createElement('img')
            let b = document.createElement('b')
            let br = document.createElement('br')
            let span = document.createElement('span')
            parentDiv.classList.add('col', 'l3', 'm6', 's12', 'direction')
            cardDiv.classList.add('card-panel')
            rowDiv.classList.add('row')
            col1Div.classList.add('col', 'l3', 'm3', 's3')
            col2Div.classList.add('col', 'l9', 'm9', 's9')
            ul.classList.add('collapsible')
            img.classList.add('responsive-img')
            img.src = direction.avatar != null ? direction.avatar : '/static/images/avatar.png'
            b.textContent = direction.name
            span.textContent = `Titular: ${direction.titular}`
            col1Div.append(img)
            col2Div.append(b, br, span)
            rowDiv.append(col1Div, col2Div)
            cardDiv.append(rowDiv, ul)
            parentDiv.append(cardDiv)
            if (direction.activities != null) {
                direction.activities.forEach(activity => {
                    let li = document.createElement('li')
                    li.className = `sem-${activity.priority}`
                    let div = document.createElement('div')
                    let i = document.createElement('i')
                    let span = document.createElement('span')
                    div.classList.add('collapsible-header')
                    if (activity.is_cancelled) div.classList.add('cancelled')
                    i.classList.add('material-icons')
                    i.textContent = 'spellcheck'
                    span.classList.add('badge', 'white-text')
                    span.style.backgroundColor = activity.color
                    span.textContent = activity.percent + '%'
                    div.append(i, span)
                    span.before(activity.name)
                    li.append(div)
                    ul.append(li)
                })
            }
            cont_directions.append(parentDiv)
        })
    }

    function showActivitiesSlider(data) {
        $('.directions-slider .direction').remove()
        data.forEach(direction => {
            let parentDiv = document.createElement('div')
            let rowDiv = document.createElement('div')
            let col1Div = document.createElement('div')
            let col2Div = document.createElement('div')
            let img = document.createElement('img')
            let h5 = document.createElement('h5')
            let h6 = document.createElement('h6')
            let ul = document.createElement('ul')
            parentDiv.classList.add('direction')
            rowDiv.classList.add('row')
            col1Div.classList.add('col', 'l2', 'center-align')
            col2Div.classList.add('col', 'l10')
            img.classList.add('responsive-img')
            img.src = direction.avatar != null ? direction.avatar : '/static/images/avatar.png'
            ul.classList.add('collapsible')
            h5.textContent = direction.name
            h6.textContent = `Titular: ${direction.titular}`
            col1Div.append(img)
            col2Div.append(h5, h6)
            rowDiv.append(col1Div, col2Div)
            parentDiv.append(rowDiv, ul)
            if (direction.activities != null) {
                direction.activities.forEach(activity => {
                    let li = document.createElement('li')
                    let div = document.createElement('div')
                    let i = document.createElement('i')
                    let span = document.createElement('span')
                    let priority = document.createElement('div')
                    priority.className = `priority z-depth-1 ${activity.priority}`
                    div.classList.add('collapsible-header')
                    if (activity.is_cancelled) div.classList.add('cancelled')
                    i.classList.add('material-icons')
                    i.textContent = 'spellcheck'
                    span.classList.add('badge', 'white-text')
                    span.style.backgroundColor = activity.color
                    span.textContent = activity.percent + '%'
                    div.append(i, span)
                    span.before(activity.name)
                    span.append(priority)
                    li.append(div)
                    ul.append(li)
                })
            }
            $('.directions-slider').slick('slickAdd', parentDiv)
        })
    }

    // function orderObjs(data) {
    //     let aux;
    //     for (let i = 0; i < data.length - 1; i++) {
    //         for (let j = 0; j < data.length - 1; j++) {
    //             if (data[j].percent > data[j + 1].percent) {
    //                 aux = data[j]
    //                 data[j] = data[j + 1]
    //                 data[j + 1] = aux
    //             }
    //         }
    //     }
    //     return data
    // }
</script>
{% endblock %}

templates/base/nueva_actividad_email.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nueva actividad asignada</title>
    <style>
        body {
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }

        img {
            width: 100%;
            max-width: 728px;
            height: 70px;
        }

        .container {
            width: 100%;
            max-width: 728px;
        }

        .text {
            text-align: center;
        }

        .estimado {
            margin-left: 5%;
        }

        .container-text {
            margin: auto;
            width: 80%;
            word-wrap: break-word;
            max-height: ;
        }
    </style>
</head>

<body>
    <div class="container">
        <img src="http://controlsedec.tabasco.gob.mx/static/images/banner-email.webp" alt="">
        <br>
        <br>
        <h4 class="estimado">Estimado(a): {{to_user}}</h4>
        <div class="container-text">
            <p class="text">Se le ha asignado una nueva actividad por <b>{{from_user}}</b>.
                Le invitamos a <a href="http://controlsedec.tabasco.gob.mx">acceder al sistema de
                    control</a> para ver más detalles.
            </p>
        </div>
        <br>
        <br>
        <img src="http://controlsedec.tabasco.gob.mx/static/images/footer-email.webp" alt="">
    </div>
</body>

</html>

templates/base/registro.html
{% extends 'base/base.html' %}
{% load customtags %}
{% load static %}
{% block title %}Semáforo de actividades | Registro{% endblock %}
{% block extrastyles %}
.avatar-filter{
filter: opacity(0.1);
}
#registroP{
margin-top:7%;
}
#registro{
padding: 0px 25px 0 25px;
}
.vino{
background-color: #892541;
}
.vino:hover{
background-color: #892541;
}
.vino:focus{
background-color: #892541;
}
button.btn, a.btn{
width : 100%;
}
{% endblock %}
{% block navbar %}{% endblock %}
{% block maincontent %}
<div class="container">
    <div class="row" id="registroP">
        <div class="col offset-l1 l10 z-depth-1 animated fadeIn" id="registro">
            <h4 class="center-align">Registro de usuarios</h4>
            <div class="divider"></div>
            <br>
            <div class="row">
                <div class="col l5 m12 s12">
                    <img class="responsive-img" src="{% static 'images/logo.png' %}" alt="">
                    <br><br>
                    <img src="{% static 'images/avatar.png' %}" alt="" id="avatar" class="avatar-filter responsive-img">
                </div>
                <div class="col l7 m12 s12">
                    <form action="" id="formUser" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-field">
                            {% selectDirectAll %}
                        </div>
                        <div class="row">
                            <div class="col l6 m12 s12">
                                <div class="input-field">
                                    {{fUsuario.first_name}}
                                    <label for="id_first_name">Ingrese su nombre</label>
                                </div>
                            </div>
                            <div class="col l6 m12 s12">
                                <div class="input-field">
                                    {{fUsuario.last_name}}
                                    <label for="id_last_name">Ingrese su apellido</label>
                                </div>
                            </div>
                        </div>
                        <div class="input-field">
                            {{fUsuario.username}}
                            <label for="id_username">Ingrese nombre de usuario</label>
                        </div>
                        <div class="input-field">
                            {{fUsuario.password}}
                            <label for="id_password">Ingrese contraseña</label>
                        </div>
                        <div class="file-field input-field">
                            <div class="btn vino">
                                <span>Imagen</span>
                                {{fUsuario.avatar}}
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col l6 m6 s12">
                                <button id="saveUser" class="btn vino right">Registrar</button>
                            </div>
                            <div class="col l6 m6 s12">
                                <a href="{% url 'login' %}" class="btn grey">Volver</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrafunctions %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
        registerUser()
        formRegisUser()
    });
</script>
{% endblock %}

templates/base/validaciones.html
{% load staticfiles %}
<script>
	function toastError(msj = "Desconocido"){
		swal({
			toast: true,
			type: 'error',
 	 		title: '<h6>'+msj+'</h6>',
			position: 'top-end',
  			showConfirmButton: false,
  			timer: 5000
		});
	}
	function toastSuccess(msj = "Desconocido"){
		swal({
			toast: true,
			type: 'success',
 	 		title: msj,
			position: 'top-end',
  			showConfirmButton: false,
  			timer: 5000
		});
	}
	function toastWarning(msj = "Desconocido"){
		swal({
			toast: true,
			type: 'warning',
 	 		title: msj,
			position: 'top-end',
  			showConfirmButton: false,
  			timer: 5000
		});
	}
	function toastNormal(msj = "Desconocido"){
		swal({
			toast: true,
			type: 'info',
 	 		html: msj,
			position: 'top-end',
  			showConfirmButton: true,
  			// timer: 5000
		});
	}
</script>

{% if messages %}
	{% for message in messages %}
		{% if message.tags == 'error' %}  
			<script> toastError("{{ message|safe }}"); </script>
		{% endif %} 
		{% if message.tags == 'success' %}
			<script> toastSuccess("{{ message|safe }}") </script>
		{% endif %}
		{% if message.tags == 'warning' %}
		<script> toastWarning("{{ message|safe }}") </script>
		{% endif %}
		{% if message.tags == 'info' %}
		<script> toastNormal("{{ message|safe }}") </script>
		{% endif %}
	{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
	<h6>Por favor, corrija los siguientes errores:</h6>
	<ul>
	{% for field in form %}
	    {% if field.errors %}
	        {% for error in field.errors %}
	    <li><strong>{{field.label}} </strong>-<a href="#id_{{ field.name }}"> {{ error|escape }}</a></li>
	        {% endfor %}
	    {% endif %}
	{% endfor %}
	</ul>
	{% if form.non_field_errors %}
	    {{ form.non_field_errors }}
	{% endif %}
</div>
{% endif %}