apps/direccion/urls.py
from django.urls import path
from .views import (vPrincipal, vPrinDirec, vPerfil, vCambiarAvatar, vCambiarNombreUsuario, vCambiarPassword, vCorreosNotificacion, vActividadEstatus,
                    vRegistroActividades, vEliminarActividades, vEditarActividad, vObtenerActividades,
                    vEditarCheckObjetivo, vEliminarObjetivo, vEditarObjetivo, vAgregarObjetivos, vEditarComentario,
                    vAgregarEvidencias, vEliminarEvidencias, vEditarPrioridad)
from .download_evidences import descargarEvidenciasZip
app_name = 'direccion'

urlpatterns = [
    path('', vPrinDirec, name = 'prinDirect'),
    path('perfil/', vPerfil, name = 'perfil'),
    path('actividades/', vPrincipal, name = 'principal'),
    #Activities
    path('actividad/agregar', vRegistroActividades, name = 'rActividad'),
    path('actividad/<int:id>/eliminar', vEliminarActividades, name = 'eActividad'),
    #Objetivos
    path('actividad/objetivo/<int:id>/eliminar', vEliminarObjetivo, name = 'eObjetivo'),
    #Evidencias
    path('actividad/evidencias/agregar', vAgregarEvidencias, name = 'rEvidencia'),
    path('actividad/evidencias/<int:id>/eliminar', vEliminarEvidencias, name = 'eEvidencia'),
    path('actividad/<int:id>/evidencias/descargar', descargarEvidenciasZip, name = 'desEvidencias'),
    #Ajax
    path('ajax/actividad/objetivo/editarcheck', vEditarCheckObjetivo),
    path('ajax/actividad/<int:id>/editar', vEditarActividad, name = 'edActividad'),
    path('ajax/actividad/objetivo/<int:id>/editar', vEditarObjetivo, name = 'edObjetivo'),
    path('ajax/actividad/objetivo/agregar', vAgregarObjetivos, name = 'aObjetivo'),
    path('ajax/actividades/', vObtenerActividades, name = 'obActividades'),
    path('ajax/actividad/<int:id>/comentarios/editar', vEditarComentario, name = 'eComentario'),
    path('ajax/actividad/<int:id>/status/editar', vActividadEstatus, name = 'edEstatusAct'),
    path('ajax/actividad/prioridad', vEditarPrioridad),
    #Acciones del perfil
    path('titular/avatar/cambiar', vCambiarAvatar, name = 'eAvatar'),
    path('titular/nombre/cambiar', vCambiarNombreUsuario, name = 'eNombreUsu'),
    path('titular/password/cambiar', vCambiarPassword, name = 'ePassword'),
    path('titular/correos/editar', vCorreosNotificacion, name = 'edCorreoNoti'),
]

semaforo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.direccion.views import vLogin, vLogout, vRegistroUsuarios


urlpatterns = [
    path('', vLogin, name = 'login'),
    path('direccion/', include('apps.direccion.urls', namespace = 'direccion')),
    path('admin/', include('apps.admin.urls', namespace = 'admin')),
    path('logout/', vLogout, name = 'logout'),
    path('registro/', vRegistroUsuarios, name = 'rUsuario'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/direccion/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Direcciones(models.Model):
    nombre = models.CharField(max_length = 100)
    codename = models.CharField(max_length = 5)
    see_in_select = models.BooleanField(default = True)
    see_in_list = models.BooleanField(default = True)
    is_active = models.BooleanField(default = True)
    titular = models.OneToOneField('direccion.Usuarios', on_delete = models.CASCADE, null = True, blank = True)
    subdireccion = models.ForeignKey('self', on_delete = models.SET_NULL, null = True, blank = True, related_name = 'subdir')
    def __str__(self):
        return '{}'.format(self.nombre)

class Usuarios(AbstractUser):
    direccion = models.ForeignKey(Direcciones, null = True, blank = True, on_delete = models.PROTECT)
    avatar = models.ImageField(upload_to = 'avatar/', null = True, blank = True)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

class Permisos(models.Model):
    assign_all = models.BooleanField(default = False)
    see_all = models.BooleanField(default = False)
    see_panel = models.BooleanField(default = False)
    delete_all = models.BooleanField(default = False)
    change_priority = models.BooleanField(default = False)
    usuario = models.OneToOneField(Usuarios, blank = True, null = True, on_delete = models.CASCADE, related_name = 'permisos')

class Actividades(models.Model):
    class Meta:
        ordering = ['prioridad', '-timestamp']

    prioridad_choices = [
        (1, 'Alta'),
        (2, 'Media'),
        (3, 'Baja')
    ]
    nombre = models.CharField(max_length = 500)
    folio = models.CharField(max_length = 10, null = True, blank = True)
    timestamp = models.DateTimeField(auto_now_add = True)
    comentarios = models.CharField(max_length = 700, null = True, blank = True,  default = '')
    prioridad = models.SmallIntegerField(default = 2, choices = prioridad_choices)
    direccion = models.ForeignKey(Direcciones, null = True, blank = True, related_name = 'actividades' , on_delete = models.CASCADE)
    is_cancelled = models.BooleanField(default = False)    
    usuario = models.ForeignKey(Usuarios, blank = True, on_delete = models.CASCADE)

    def get_priority_class(self):
        if self.prioridad == 1:
            return 'high'
        elif self.prioridad == 2:
            return 'medium'
        elif self.prioridad == 3:
            return 'low'
        else:
            return 'none'

    def get_priority(self):
        return dict(self.prioridad_choices).get(self.prioridad, 'No especificado')

    def get_porcent(self):
        total = self.objetivos.count()
        total_done = self.objetivos.filter(is_done = True).count()
        return getPercentActivity(total_done, total)
    
    def get_light(self):
        total = self.objetivos.count()
        total_done = self.objetivos.filter(is_done = True).count()
        return getLightActivity(total_done, total)

def act_directory_path(instance, filename):
    return 'evidencias/{0}/{1}'.format(instance.actividad.folio,filename)

class Evidencias(models.Model):
    evidencia = models.FileField(upload_to = act_directory_path, null = True, blank = True)
    nombre = models.CharField(max_length = 500)
    timestamp = models.DateTimeField(auto_now_add = True)
    actividad = models.ForeignKey(Actividades, null = True, blank = True, related_name = 'evidencias' , on_delete = models.CASCADE)

class Objetivos(models.Model):
    nombre = models.CharField(max_length = 500)
    is_done = models.BooleanField(default = False)
    actividad = models.ForeignKey(Actividades, null = True, blank = True, related_name = 'objetivos' , on_delete = models.CASCADE)

def getPercentActivity(num, total):
    try:
        percent = (100 * num)/total
        return round(percent)
    except:
        return 0

def getLightActivity(num, total):
    red_color = '#f44336'
    green_color = '#4caf50'
    yellow_color = '#ffeb3b'
    green_light = 100
    yellow_light = 70
    try:
        percent = getPercentActivity(num, total)
        if percent == green_light:
            return green_color
        elif percent < green_light and percent >= yellow_light:
            return yellow_color
        elif percent < yellow_light:
            return red_color
    except:
        return red_color

class Correos_Notificacion(models.Model):
    correo_inst = models.EmailField(null = True, blank = True)
    correo_per = models.EmailField(null = True, blank = True)
    usuario = models.OneToOneField(Usuarios, related_name = 'correos', null = True, blank = True, on_delete = models.CASCADE)

apps/direccion/views.py
# Python
import os
import re
# Django
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login as auth_login , authenticate, logout, update_session_auth_hash
from django.contrib import messages
from django.db.models import Count
from django.utils import timezone
# App direccion
from .models import Usuarios, Permisos, Actividades, Objetivos, Direcciones, Evidencias, getPercentActivity, getLightActivity, Correos_Notificacion
from .forms import fRegistroUsuariosDir, fCorreosNotificacion
from .validate_file import validate_file_type, validate_img_type
from .send_email import send_notification_mail
patron = re.compile(r'^\d{4}$')

def vLogin(request):
    if request.user.is_authenticated:
	    return redirect('logout')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        autenticar = authenticate(username = username, password = password)
        if autenticar is not None:
            auth_login(request, autenticar)
            if request.user.is_superuser :
                return redirect('admin:prinAdmin')
            elif request.user.direccion is not None:
                return redirect('direccion:prinDirect')
        else:
            messages.add_message(request, messages.ERROR,'Usuario y/o contraseña no válidos')
        return redirect('login')
    return render(request, 'base/login.html')

def vLogout(request):
    logout(request)
    return redirect('login')

@login_required
def vPrinDirec(request):
    current_year = request.GET.get('year', str(timezone.localtime().date().year))
    if patron.search(current_year) is None:
        current_year = timezone.localtime().date().year
    context = {'current_year': current_year}
    return render(request, 'direccion/prinDirec.html', context)

# Verifica si el usuario tiene permiso para ver el panel
def see_panel_test(user):
    if user.is_superuser:
        return True
    elif Permisos.objects.filter(usuario = user).exists():
        if user.permisos.see_panel:
            return True
        else: 
            return False
    else:
        return False      

@login_required
@user_passes_test(see_panel_test, login_url = '/direccion')
def vPrincipal(request):
    current_year = timezone.localtime().date().year
    context = {'direcciones': Direcciones.objects.exclude(codename = 'sg'), 'current_year': current_year}
    return render(request, 'base/main.html', context)

@login_required
def vPerfil(request):
    fcorreo_noti = fCorreosNotificacion()
    return render(request, 'direccion/perfil.html', {'fcorreo_noti' : fcorreo_noti})

def vRegistroUsuarios(request):
    if request.method == 'POST':
        fUsuario = fRegistroUsuariosDir(request.POST, request.FILES)
        if fUsuario.is_valid():
            try:
                usuario = fUsuario.save(commit = False)
                pass_unhash = usuario.password
                usuario.set_password(usuario.password)
                usuario.save()
                usuario.direccion.titular = usuario
                usuario.direccion.save()
            except expression as identifier:
                print(identifier)
                messages.error(request,'Ha ocurrido un error. Intente de nuevo por favor')
                return redirect('rUsuario')    
            autenticar = authenticate(username = usuario.username, password = pass_unhash)
            if autenticar is not None:
                auth_login(request, autenticar)
                if request.user.direccion is not None:
                    return redirect('direccion:prinDirect')
                    messages.success(request, 'Registro con éxito - Bienvenido(a)')
                else:
                    print('ide1')
                    messages.error(request,'Ha ocurrido un error. Intente de nuevo por favor')
                    return redirect('login')
            else:
                print('ide2')
                messages.error(request,'Usuario y/o contraseña no válidos')
                return redirect('login')
        else:
            print('ide3')
            messages.error(request,'Ha ocurrido un error. Intente de nuevo por favor')
            return redirect('rUsuario')
    else:
        fUsuario = fRegistroUsuariosDir()
        context = {'fUsuario' : fUsuario}
    return render(request, 'base/registro.html', context)

# Verificar estas funciones
@login_required
def vCambiarAvatar(request):
    if request.method == 'POST': 
        usuario = request.user
        avatar = request.FILES.get('avatar')
        if avatar is not None:
            if validate_img_type(avatar):
                if usuario.avatar:
                    old_avatar = usuario.avatar.path
                    usuario.avatar = avatar
                    usuario.save()
                    try:
                        deleteFile(old_avatar)
                        messages.success(request, 'Avatar cambiado exitosamente')
                    except:
                        messages.error(request, 'Ha ocurrido un error, intente de nuevo')
                else:
                    usuario.avatar = avatar
                    usuario.save()
                    messages.success(request, 'Avatar cambiado exitosamente')
            else:
                messages.warning(request, 'Imagen inválida')
        else:
            messages.warning(request, 'Debe agregar una imagen')
    else:
        messages.error(request, 'Ha ocurrido un error, intente de nuevo')
    return redirect('direccion:perfil')

@login_required
def vCambiarNombreUsuario(request):
    if request.method == 'POST':
        nombre = request.POST.get('name')
        apellido = request.POST.get('last_name')
        usuario = request.user
        if len(nombre) > 0:
            usuario.first_name = nombre
            usuario.last_name = apellido
            usuario.save()
            messages.success(request, 'Nombre cambiado exitosamente')
        else:
            messages.error(request, 'Debe de ingresar su nombre al menos')
    else:
        messages.error(request, 'Ha ocurrido un error, intente de nuevo')
    return redirect('direccion:perfil')

@login_required
def vCambiarPassword(request):
    if request.method == 'POST':
        current_pass = request.POST.get('current_pass')
        new_pass = request.POST.get('new_pass')
        if request.user.check_password(current_pass):
            request.user.set_password(new_pass)
            request.user.save(update_fields=['password'])
            update_session_auth_hash(request, request.user)
            messages.success(request, 'Contraseña cambiada exitosamente')
        else:
            messages.warning(request, 'La contraseña no coincide con la actual. Intente de nuevo')
            return redirect('direccion:perfil')
    else:
        messages.error(request, 'Ha ocurrido un error inesperado')
    return redirect('login')

@login_required
def vCorreosNotificacion(request):
    if request.method == 'POST':
        usuario = request.user
        fcorreos = fCorreosNotificacion(request.POST)
        if fcorreos.is_valid():
            correo = fcorreos.save(commit = False)
            obj, created = Correos_Notificacion.objects.update_or_create(
                usuario = usuario,
                defaults={'correo_inst': correo.correo_inst, 'correo_per': correo.correo_per}
            )
            messages.success(request, 'Cambios guardados exitosamente')
        else:
            messages.error(request, 'No se guardó ningún cambio. Intente de nuevo')
    return redirect('direccion:perfil')

#---Actividades
@login_required
def vRegistroActividades(request):
    if request.method == 'POST':
        nombre = request.POST.get('act-name')
        direccion = request.POST.get('direccion', None)
        prioridad = request.POST.get('prioridad', None)
        objs = request.POST.getlist('obj-name')
        objs_check = request.POST.getlist('obj-check')
        evidencias = request.FILES.getlist('evidencias')
        folio = 'ACT-'
        try:
            if direccion is None:
                direccion = request.user.direccion
            else:
                direccion = Direcciones.objects.get(id__exact = direccion)
            activity = Actividades.objects.create(nombre = nombre, direccion = direccion, usuario = request.user, prioridad = prioridad)
            activity.folio = folio + str(activity.id)
            activity.save()
            for obj, checked in zip(objs, objs_check):
                if len(obj) > 0:
                    pass
                    Objetivos.objects.create(nombre = obj, is_done = trueOrFalse(checked), actividad = activity)
            for evidencia in evidencias:
                Evidencias.objects.create(evidencia = evidencia, nombre = evidencia.name, actividad = activity)
            send_notification_mail(request.user, activity.direccion.titular)
            messages.success(request, 'Actividad agregada exitosamente')
        except Exception as e:
            print(e)
            messages.error(request, 'Ha ocurrido un error, inténtelo de nuevo')
    return redirect('direccion:prinDirect')

def vEditarActividad(request, id):
    if request.is_ajax():
        nombre = request.POST.get('new_name')
        try:
            act = Actividades.objects.get(id = id)
            act.nombre = nombre
            act.save()
            info = {
                'status' : 'success',
                'text' : 'Actividad actualizada exitosamente'
            }
        except:
            info = {
                'status' : 'error',
                'text' : 'Al parecer algo salió mal. Intente de nuevo'
            }
    else:
        info = {
            'status' : 'error',
            'text' : 'Al parecer algo salió mal. Intente de nuevo'
        }    
    return JsonResponse(info, safe = False)

templates/direccion/perfil.html
{% extends 'base/base.html' %}
{% load static %}

{% block extrastyles %}
a#name-modal > i{
color: #892541;
}
.title-direc{
color: #892541;
}
.vino{
background-color: #892541;
}
.vino:hover{
background-color: #892541;
}
.vino:focus{
background-color: #892541;
}
{% endblock %}
{% block title %}Semáforo de activades | Perfil{% endblock %}
{% block extralist %}
<li><a href="{% url 'direccion:prinDirect' %}">Principal</a></li>
{% endblock %}
{% block extralistmob %}
<li><a href="{% url 'direccion:prinDirect' %}">Principal</a></li>
{% endblock %}
{% block maincontent %}
<div class="container">
    <br><br><br>
    <div class="row">
        <div class="center-align col l4 offset-l4 m12 s12">
            {% if user.avatar %}
            <img src="{% get_media_prefix %}{{user.avatar}}" alt="" class="responsive-img">
            {% else %}
            <img src="{% static 'images/avatar.png' %}" alt="" class="avatar-filter responsive-img">
            {% endif %}
            <a href="#avatar-modal" class="right modal-trigger">cambiar foto</a>
        </div>
    </div>
    <div class="col l8 offset-l2 m12 s12">
        <h4 class="center-align title-direc">{{user.get_full_name}}&nbsp;<a href="#name-modal" class="modal-trigger"><i
                    class="material-icons">edit</i></a></h4>
        <h5 class="center-align">{{user.direccion.nombre}}</h5>
        <div class="row">
            <div class="col l10 offset-l1 m12 s12">
                <br>
                <br>
                <h6>Usuario asignado: <b class="title-direc">{{user.username}}</b></h6>
                <br>
                <br>
                <h5>Cambiar contraseña</h5>
                <div class="divider"></div>
                <br>
                <div class="row">
                    <form action="{% url 'direccion:ePassword' %}" method="post" id="pass-form">
                        {% csrf_token %}
                        <div class="col l6 m12 s12">
                            <div class="input-field">
                                <input type="password" name="current_pass" id="current_pass">
                                <label for="current_pass">Ingrese contraseña actual</label>
                            </div>
                        </div>
                        <div class="col l6 m12 s12">
                            <div class="input-field">
                                <input type="password" name="new_pass" id="new_pass">
                                <label for="new_pass">Ingrese nueva contraseña</label>
                            </div>
                        </div>
                        <p class="center-align">Al cambiar su contraseña será redireccionado al inicio de sesión</p>
                        <div class="row">
                            <div class="col l12">
                                <button class="btn right vino" id="change-pass">Cambiar</button>
                            </div>
                        </div>
                    </form>
                </div>
                <br>
                <h5>Correos para notificación</h5>
                <div class="divider"></div>
                <br>
                <div class="row">
                    <form action="{% url 'direccion:edCorreoNoti' %}" method="post" id="emails-form">
                        {% csrf_token %}
                        <div class="col l6 m12 s12">
                            <div class="input-field">
                                <input type="email" name="correo_inst" maxlength="254"
                                    value="{% if user.correos.correo_inst %}{{user.correos.correo_inst}}{% endif %}"
                                    id="id_correo_inst">
                                <label for="inst_email">Correo institucional</label>
                                <span class="helper-text">Opcional</span>
                            </div>
                        </div>
                        <div class="col l6 m12 s12">
                            <div class="input-field">
                                <input type="email" name="correo_per" maxlength="254"
                                    value="{% if user.correos.correo_per %}{{user.correos.correo_per}}{% endif %}"
                                    id="id_correo_per">
                                <label for="pers_email">Correo personal</label>
                                <span class="helper-text">Opcional</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col l12">
                                <button class="btn right vino" id="change-email">Guardar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal edit avatar -->
<div id="avatar-modal" class="modal white">
    <div class="modal-content">
        <form action="{% url 'direccion:eAvatar' %}" method="POST" id="avatar-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="file-field input-field">
                <div class="btn vino">
                    <span>Seleccione imagen</span>
                    <input type="file" name="avatar" accept="image/jpeg, image/png">
                </div>
                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text">
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="waves-effect waves-light btn vino" id="change-avatar">Subir</button>
    </div>
</div>
<!-- Modal edit name -->
<div id="name-modal" class="modal white">
    <div class="modal-content">
        <form action="{% url 'direccion:eNombreUsu' %}" method="post" id="name-user-form">
            {% csrf_token %}
            <div class="row">
                <div class="col l6 input-field">
                    <input type="text" name="name" id="name" value="{{user.first_name}}">
                    <label for="name">Ingrese su nombre</label>
                </div>
                <div class="col l6 input-field">
                    <input type="text" name="last_name" id="last_name" value="{{user.last_name}}">
                    <label for="last_name">Ingrese su apellido</label>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="waves-effect waves-light btn vino" id="edit-name-user">Guardar</button>
    </div>
</div>
{% endblock %}
{% block extrafunctions %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var modal = document.querySelectorAll('.modal');
        var modal_instances = M.Modal.init(modal);
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
        editUser()
        // var select = document.querySelectorAll('#id_direccion');
        // var select_instances = M.FormSelect.init(select);
        // var dropdown = document.querySelectorAll('.dropdown-trigger');
        // var dropdown_instances = M.Dropdown.init(dropdown);
    });
</script>
{% endblock %}

templates/direccion/prinDirec.html
{% extends 'base/base.html' %}
{% load customtags %}
{% block title %}Semáforo de actividades | {{user.direccion}} {% endblock %}
{% block extrastyles %}
a.btn-floating{
background-color: #892541;
}
a.btn-floating:hover{
background-color: #892541;
}
.vino{
background-color: #892541;
}
.vino:hover{
background-color: #892541;
}
.vino:focus{
background-color: #892541;
}
span.badge {
min-width: 4rem;
}
.title-direc{
color: #892541;
}
table {
table-layout: fixed;
}
td{
overflow-wrap: break-word;
}
.bn-cont{
margin: 5px;
}
.txt-vino{
color: #892541;
}
{% endblock %}
{% block direcName %}{{user.direccion.nombre}}{% endblock %}
{% block extralist %}
<li><a href="{% url 'direccion:perfil' %}">Configuraciones</a></li>
{% endblock %}
{% block extralistmob %}
<li><a href="{% url 'direccion:perfil' %}">Configuraciones</a></li>
{% endblock %}
{% block maincontent %}
<div class="bn-cont">
    <form method="get" id="formYear">
        <select class="browser-default right" name="year" id="filter-year" style="width: 100px;">
            <option value="" selected>----</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
        </select>
    </form>
</div>
<div class="container">
    <br>
    <br>
    <h4 class="center-align title-direc">{{user.direccion.nombre}}</h4>
    <h5 class="center-align txt-vino num-year">{{current_year}}</h5>
    <br>
    <br>
    {% if user.permisos.see_all %}
    {% showAllDirecActivities user current_year %}
    {% else %}
    {% showFilterDirectActivities user current_year %}
    {% if user.direccion.subdir.count > 0 %}
    <br><br>
    <h5>Direcciones asignadas</h5>
    <div class="divider"></div>
    <br><br><br>
    {% showAllDirecActivities user current_year True %}
    {% endif %}
    {% endif %}
    {% comment %}{% if user.permisos.assign_all %}{% endcomment %}
    <!-- Button new activity -->
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect waves-light modal-trigger" href="#act-modal"><i
                class="material-icons">add</i></a>
    </div>
    {% comment %}{% endif %}{% endcomment %}
    <!-- Modal activity form -->
    <div id="act-modal" class="modal modal-fixed-footer white">
        <div class="modal-content">
            <h5>Registro de actividad</h5>
            <div class="divider"></div>
            <div class="row">
                <div class="col l10 offset-l1">
                    <form action="{% url 'direccion:rActividad' %}" method="post" id="act-form"
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        <br>
                        <div class="input-field">
                            <input type="text" name="act-name" id="act-name">
                            <label for="act-name">Nombre</label>
                        </div>

                        {% if user.permisos.assign_all %}
                        {% selectDirectFilter %}
                        {% else %}
                        {% selectDirectFilter user %}
                        {% endif %}

                        <div class="input-field">
                            <select name="prioridad" id="id_prioridad">
                                <option value="1">Alta</option>
                                <option value="2">Media</option>
                                <option value="3" selected>Baja</option>
                            </select>
                            <label for="id_prioridad">Seleccione una prioridad</label>
                        </div>
                        <br>
                        <h5 class="center-align">Objetivos</h5>
                        <a class="btn right vino" id="add-objs"><i class="material-icons">add</i></a>
                        <br><br>
                        <div id="act-objs">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th class="right-align">Hecho</th>
                                        <th class="center-align">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                        <br><br>
                        <h5 class="center-align">Evidencias</h5>
                        <div class="file-field input-field">
                            <div class="btn vino">
                                <span>Seleccionar</span>
                                <input type="file" name="evidencias" id="evidencias" multiple>
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path" type="text">
                                <span class="helper-text">10 MB es el peso límite por archivo</span>
                            </div>
                        </div>
                        <ul class="collection" id="files">
                        </ul>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a href="#!" class="waves-effect waves-light btn vino" id="save-act" href="#act-modal">Guardar</a>
        </div>
    </div>
</div>
{% endblock %}
{% block extrafunctions %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        formActivity()
        document.querySelector('#filter-year').addEventListener('change', function () {
            let regEX = /^\d{4}$/
            let year = this.value
            let formYear = document.querySelector('#formYear')
            if (regEX.test(year)) {
                formYear.submit()
            }
        })
        var modal = document.querySelectorAll('.modal');
        var modal_instances = M.Modal.init(modal);
        var collapsible = document.querySelectorAll('.collapsible');
        var collapsible_instances = M.Collapsible.init(collapsible);
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems);
        var select = document.querySelectorAll('.input-field select');
        var select_instances = M.FormSelect.init(select);

    });
</script>
{% endblock %}